# Generated by Django 5.0.3 on 2026-04-16 21:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pet_id', models.CharField(max_length=100)),
                ('pet_source', models.CharField(choices=[('local', 'Local'), ('thedogapi', 'TheDogAPI')], max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='customers.customer')),
            ],
            options={
                'ordering': ['requested_at'],
                'indexes': [models.Index(fields=['requested_at'], name='adoptions_a_request_83e65c_idx')],
            },
        ),
    ]
